### ISSUE TITLE
Полная версия

### ISSUE THREAD

**Issue by foshechka** [andrey-helldar/vk-music#1]
Доброго времени! Можно получить полную версию скрипта? Возникают трудности с установкой композера и т. п.. Кстати, вроде как скоро должны открыть раздел аудио ...

**Comment by andrey-helldar** [comment]
Добрый! В этом репозитории как раз полностью весь исходный код проекта.
По поводу раздела аудио, его наоборот прикрыли, чтобы монетизировать. Нынче стоимость прослушивания аудио составляет 149 рублей в месяц и лишь 15 минут в сутки бесплатно, и то только в официальном приложении ВК.

**Comment by foshechka** [comment]
Я имел ввиду, полную версию скрипта без дополнительных установок композера, npm и т. д.. У меня с этим трудности. А возможно этот каталог переделать под локальную загрузку и хранение аудио на своих серверах? Чтобы описание артиста подтягивать с ластфм например?

**Comment by andrey-helldar** [comment]
С композером еще как-то можно, а вот с NPM - кто намеренно будет ~130к файлов в архив упаковывать?

Переписать на ласт.фм можно - код перед вами. Нужно всего лишь механику в него прописать.

А, вообще, рекомендую использовать [свежую 5.6 версию фреймворка](laravel.com/docs/5.6/) для работы с нуля, так как текущий проект написан на версии 5.3.

**Comment by andrey-helldar** [comment]
Выложил файлы на собранный композером проект: https://github.com/andrey-helldar/vk-music/releases/tag/1.0.0

**Comment by foshechka** [comment]
Огромная благодарность! Сколько будет стоить ваши услуги, если переделать проект под наши нужды?

**Comment by andrey-helldar** [comment]
Зависит от конкретного ТЗ. В какую сумму планируете уложиться?

**Comment by foshechka** [comment]
Можно глянуть как-то скрин твоего рабочего проекта? Как там все было?

**Comment by andrey-helldar** [comment]
https://github.com/andrey-helldar/vk-music/blob/master/SCREENSHOTS.md

**Comment by foshechka** [comment]
Я напишу, что мы бы хотели изменить, а ты предложишь цену за свои услуги:
1. Локальная загрузка и хранение аудиозаписей с возможностью скачать
2. Редактирование аудиозаписей по типу ВК
3. Функциональный фиксированный плеер по типу ВК
4. Расположение Треков по типу ВК
5. Описание артиста (биография, дискография и т. д..) из Ласт ФМ
6. WaveForm трека на основе html5 (опционально)

Это вкратце, если сойдемся по цене, то готовы на постоянное сотрудничество и разработку.

**Comment by andrey-helldar** [comment]
Это не меньше сотни будет.

**Comment by foshechka** [comment]
Допустим. Дай свой телеграмм.

**Comment by andrey-helldar** [comment]
@helldar16:57, 7 марта 2018 г., foshechka <notifications@github.com>:Допустим. Дай свой телеграмм.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




Best Regards    Andrey Helldar
